### ISSUE TITLE
The init function in RTCMultiConnect.js has a line this.connection = new RTCPeerConnection(this.iceServers, this.optionalArgument); On this line RTCPeerConnection is undefined.  

### ISSUE THREAD

**Issue by creedrahul** [muaz-khan/Canvas-Designer#5]
i have tried to debug the code by creating a new function with the same name but then i start get other errors. any help is appreciated

**Comment by muaz-khan** [comment]
`RTCPeerConnection` object is defined here:

* [https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/PeerConnection.js#L1](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/PeerConnection.js#L1)

The line you referenced is using it here:

* [https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/PeerConnection.js#L188](https://github.com/muaz-khan/RTCMultiConnection/blob/master/dev/PeerConnection.js#L188)

Please make sure that you're using this `RTCMultiConnection` file via `rawgit.com` or download to local system:

* [https://github.com/muaz-khan/RTCMultiConnection/blob/master/RTCMultiConnection.js](https://github.com/muaz-khan/RTCMultiConnection/blob/master/RTCMultiConnection.js)

**Comment by creedrahul** [comment]
I have downloaded the file to local system but the error is still there. i get the error from init function in RTCMulitiConnect.js. (while debugging the error is throws at line 4107 RTCMulitiConnect.js)

**Comment by muaz-khan** [comment]
Please make sure that you are NOT using `adapter.js` or similar solutions.

Open Chrome Console (ctrl+shift+i or command+option+i) and type `RTCPeerConnection`. Chrome console MUST throw error because `RTCPeerConnection` is hidden object. If it shows some kind of function then either remove `adapter.js` or modify `RTCMultiConnection.js` as following:

```javascript
var RTCPeerConnection = window.mozRTCPeerConnection || window.webkitRTCPeerConnection;
var RTCSessionDescription = window.RTCSessionDescription || window.mozRTCSessionDescription;
var RTCIceCandidate = window.RTCIceCandidate || window.mozRTCIceCandidate;
```

If you'll keep using `adapter.js` then RTCMultiConnection MAY-NOT work in latest Firefox releases. (where `mozRTCPeerConnection` is expected to be removed, soon)
